# ----------------------------------------------
# 
#   CESA - Autogenerated Timestamps on Transcripts
#
# ----------------------------------------------

# ==============================
# Packages
# ==============================

# Install (only need to install once)
#install.packages("readr")
#install.packages("stringr")
#install.packages("chron")

# Load
library(readr)
library(stringr)
library(chron)


# ==============================
# Prep
# ==============================

your_wd <- "/Users/jdraper/JessPersonal/COBIVA/CESA/timestamps"

setwd(your_wd)
getwd() # Confirm correct wd

# Getting file name list from working directory
filelist <- list.files(pattern = ".txt")

# Creating empty data frame
files <- data.frame(Name = NA, Text = NA, End_Time = NA)

# Collecting (new) names and text content into db
for (i in 1:length(filelist)) {
  files[i,1] <- paste("ts_",filelist[i], sep="") # Adding "ts_" prefix to file names (for timestamps)
  files[i,2] <- read_file(filelist[i])
}

# Reformat txt
cleanFormat <- function(txt) {
  str_c("\n", txt) %>%
    str_replace_all("\\n*", "") %>% str_replace_all("\\r*", "") %>% # --- Remove all line breaks
    str_replace_all("\\[?(\\d{2}:\\d{2}:\\d{2})\\]?\\s?", "\r\r\\1") %>% # --- Remove brackets from timestamps, add line break before
    str_replace_all("(?:(E|P):\\s){1}", "\n\n[\\1] ") %>% # --- Put speaking turns on new lines with brackets
    str_replace_all("((?<!\\r\\r)\\d{2}:\\d{2}:\\d{2}|\\d{2}:\\d{2}:\\d{2}(?!\\n|\\Z))", "") %>% # --- Remove timestamps within speaking turns
    str_replace_all("\\r\\r(?!\\d{2}:\\d{2}:\\d{2})", "") %>% # --- Removes unneccessary returns that aren't before timestamps
    str_replace("\\r\\r", "") # --- removes blank spaces above first timestamps
}

# Running function over text column of "files" data frame
files$Text <- sapply(files[,2], cleanFormat)

# ==============================
# Calculate timestamps
# ==============================

addTimestamps <- function(txt, name) {
  
  print(name)
  # vector of timestamps
  timestamps <- str_extract_all(txt, "\\d{2}:\\d{2}:\\d{2}", simplify = TRUE)[1,]
  #timestamps <- c("00:00:00", timestamps) # add starting 0
  
  # break txt into chunks
  all_chunks <- str_split(txt, "\\d{2}:\\d{2}:\\d{2}", simplify = TRUE)[1,]
  chunks <- character()
  for (i in 1:length(all_chunks)) {
    if (nchar(all_chunks[i]) > 2) {
      chunks <- c(chunks, all_chunks[i])
    }
  }
  
  # create empty list and df
  chunks_list <- list()
  all_txt <- data.frame()
  
  # for each chunk, create a data frame of txt lines and timestamps
  for (i in 1:length(chunks)) {
    all_lines <- str_split(chunks[i], "\\n\\n", simplify = TRUE)[1,]
    lines <- character()
    for (j in 1:length(all_lines)) {
      if (nchar(all_lines[j]) > 0) {
        lines <- c(lines, all_lines[j])
      }
    }
    
    chunks_list[[i]] <- data.frame(txt = lines, ts = "00:00:00")
    chunks_list[[i]]$ts[1] <- timestamps[i]
    chunks_list[[i]]$ts <- chron(times = chunks_list[[i]]$ts)
  }
  
  # now calculate
  for (i in 1:length(chunks_list)) {
    #print(i)
    n <- nrow(chunks_list[[i]]) # number of lines
    start <- chunks_list[[i]]$ts[1] # starting timestamp
    
    # set end if last in loop, else first ts of next chunk
    if (i == length(chunks_list)) {
      end <- chron(times = tail(timestamps, n=1))
    } else {
      end <- chunks_list[[i+1]]$ts[1]
    }
    
    duration <- end - start # duration of chunk
    increment <- duration/n # increment in seconds
    
    # increase timestamps by increment
    if (n > 1) {
      for (j in 2:n) {
        #print(j)
        chunks_list[[i]]$ts[j] <- chunks_list[[i]]$ts[j-1] + increment
      }
    }
    
    # append chunk df to main df
    all_txt <- rbind(all_txt, chunks_list[[i]])
  }
  
  # end time column
  all_txt$ts2 <- chron(times = NA)
  for (i in 1:nrow(all_txt)) {
    all_txt$ts2[i] <- all_txt$ts[i+1]
    if (i == nrow(all_txt)) {
      all_txt$ts2[i] <- chron(times = tail(timestamps, n=1))
    }
  }
  
  all_txt$text <- glue::glue("\r\r{all_txt$ts}.500 --> {all_txt$ts2}.000\r{all_txt$txt}")
  full_txt <- paste(all_txt$text, collapse = "")
  output_file <- paste("WEBVTT", full_txt, sep="")
}


files$Text <- mapply(addTimestamps,files[,2],files[,1])

# ==============================
# Save
# ==============================

# Set subfolder to save processed transcripts within working directory
setwd(paste0(your_wd, "/processed"))

# Function for saving files
savefile <- function (df, i) {
  write_file(df[i,2], df[i,1])
}

# Running function
for (i in 1:nrow(files)) {
  savefile(files, i)
}
